### ISSUE TITLE
[Bug résolu] [v6.1.0 - Firefox] Average calculation error

### ISSUE THREAD

**Issue by s1w2a3** [Bastian-Noel/CustomDirecte#9]
> [Bug] - Average calculation error - @s1w2a3 

**Détails techniques :**
Depuis quelques semaines, le calculateur de moyennes par matière et de générale ne fonctionne plus sur Firefox.
Dans la première ligne, trois points de suspension apparaissent, et les autres lignes sont vides pour l'emplacement de la moyenne (comme cela serait le cas sans l'extension car l'établissement a désactivé le calcul des moyennes). Il est indiqué "Erreur" là où devrait se trouver la moyenne générale. En revanche, tout fonctionne correctement sur Chrome.

**Commentaire :**
Merci pour cette extension très utile.

**Comment by Bastian-Noel** [comment]
@s1w2a3  Merci d'avoir signaler ce bug

Pour pouvoir comprendre la source de ce bug, j'aurais besion de plus d'information, peut tu rejoindre ce serveur discord pour que l'on puisse plus facilement communiquer ? : [WJtuEa97g6](https://discord.gg/WJtuEa97g6)

**Comment by s1w2a3** [comment]
@Bastian-Noel C'est fait !
